name: yandex_intensive
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_icons: ^1.1.0
  page_transition: ^1.1.7+6
  animated_bottom_navigation_bar: ^0.2.1
  fl_chart: ^0.40.5
  percent_indicator: ^3.4.0
  freezed_annotation: any
  syncfusion_flutter_maps: ^19.3.57-beta
  country_icons: ^2.0.2
  freezed: ^0.14.2
  build_runner: ^2.1.2
  json_serializable: ^4.1.4
  dio: ^4.0.4
  provider: ^6.0.1
  riverpod: ^1.0.2
  flutter_riverpod: ^1.0.2
  hooks_riverpod: ^1.0.2
  flutter_hooks: ^0.18.1
  sprintf: ^6.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  flutter_lints: ^1.0.4
  test: ^1.14.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/pictures/
    - world_map.json
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay-Light.ttf
          weight: 300
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SFProText-Medium.ttf
          weight: 500

